name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Start server (background)
        run: |
          node server/index.js &
          echo $! > server_pid.txt

      - name: Wait for healthcheck
        run: npx wait-on http://localhost:3001/api/health

      - name: Smoke test
        run: curl -s http://localhost:3001/api/health | grep -q '"ok":true'

      - name: Stop server
        if: always()
        run: |
          kill $(cat server_pid.txt) || true