name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Корневые зависимости (если нужны)
      - name: Install root deps
        run: npm ci

      # ======== Backend: feedbackFormAPI ========
      - name: Install API deps
        if: ${{ hashFiles('feedbackFormAPI/package.json') != '' }}
        run: npm ci
        working-directory: feedbackFormAPI

      - name: Start API server (background)
        if: ${{ hashFiles('feedbackFormAPI/package.json') != '' }}
        run: |
          node feedbackFormAPI/index.js > server.log 2>&1 &
          echo $! > server_pid.txt

      - name: Wait for healthcheck
        if: ${{ hashFiles('feedbackFormAPI/package.json') != '' }}
        run: npx wait-on http://localhost:3001/api/health -t 90000

      - name: Smoke test
        if: ${{ hashFiles('feedbackFormAPI/package.json') != '' }}
        run: curl -s http://localhost:3001/api/health | grep -q '"ok":true'

      - name: Show server log (debug)
        if: ${{ always() && hashFiles('feedbackFormAPI/package.json') != '' }}
        run: |
          echo "---- server.log ----"
          tail -n 200 server.log || true

      - name: Stop server
        if: ${{ always() && hashFiles('feedbackFormAPI/package.json') != '' }}
        run: kill $(cat server_pid.txt) || true