name: CI

on:
  push:
    branches: ["**"]        # запускаем на любом пуше, в т.ч. no-chat
  pull_request:
    branches: ["**"]        # и на любом PR
  workflow_dispatch:         # кнопка Run workflow в Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      # В проекте пока нет тестов — просто проверим, что всё ок
      - name: Sanity check
        run: |
          node -v
          echo "OK"